name: Docker Build and Push

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        # with:
        #   since_last_remote_commit: true 

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      
      # Build a Docker image of your application in your registry and tag the image with the $GITHUB_SHA.
      - name: Build container image
        run: docker build -t registry.digitalocean.com/weatherregistery/weatherapp:$(echo $GITHUB_SHA | head -c7) .
  
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
  
      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/weatherregistery/weatherapp:$(echo $GITHUB_SHA | head -c7)
      

