name: Docker Build and Push

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t weatherapp:latest .
          docker tag weatherapp:latest imtiaz2564/weatherapp:latest
          docker push imtiaz2564/weatherapp:latest
        env:
          DOCKER_CLI_ACI: 1
          
      - name: Login to DigitalOcean Container Registry
        run: echo ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} | docker login -u ${{ secrets.DIGITALOCEAN_REGISTRY_USERNAME }} --password-stdin registry.digitalocean.com

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/your-digitalocean-username/weatherapp:latest
        env:
          DOCKER_CLI_ACI: 1
