name: Docker Build and Push

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t weatherapp:latest .
          docker tag weatherapp:latest imtiaz2564/weatherapp:latest
          docker push imtiaz2564/weatherapp:latest
        env:
          DOCKER_CLI_ACI: 1
          
      - name: Login to DigitalOcean Container Registry
        run: |
          mkdir -p $HOME/.docker
          echo '{"auths":{"registry.digitalocean.com":{"username":"your-digitalocean-username","password":"your-digitalocean-access-token","auth":"'"$(echo -n your-digitalocean-username:your-digitalocean-access-token | base64)"'"}}}' > $HOME/.docker/config.json
        env:
          DOCKER_CONFIG: $HOME/.docker
      
        
      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/imtiazaiub1@gmail.com/weatherapp:latest
        env:
          DOCKER_CLI_ACI: 1
